"""empty message

Revision ID: 075b2fb7755e
Revises: 8b7948ec874e
Create Date: 2020-11-28 17:41:09.265057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '075b2fb7755e'
down_revision = '8b7948ec874e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tag_keyword'), 'tag', ['keyword'], unique=True)
    op.create_table('group_tag_assoc',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('group_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group_tag_assoc')
    op.drop_index(op.f('ix_tag_keyword'), table_name='tag')
    op.drop_table('tag')
    # ### end Alembic commands ###
